name: Node.js CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install
      working-directory: reactapp

    - name: Set CI to false
      run: |
        echo "CI=false" >> $GITHUB_ENV

    - name: Run build
      run: npm run build --if-present
      working-directory: reactapp

    - name: List build directory contents
      run: ls -la reactapp/build

    - name: Zip build artifacts
      run: zip -r build.zip build
      working-directory: reactapp

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: reactapp/build.zip

    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: build-artifacts
        path: .

    - name: Unzip build artifacts
      run: unzip build.zip -d build

    - name: List unzipped build directory contents
      run: ls -la build

    - name: Move build artifacts to wwwroot
      run: |
        mkdir -p $HOME/site/wwwroot
        mv build/* $HOME/site/wwwroot

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'protechfapp'
        package: $HOME/site/wwwroot
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
